# Generated by Django 2.0.4 on 2018-04-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0003_auto_20180421_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='name',
            field=models.CharField(choices=[('Done', 'Done'), ('Verify', 'Verified'), ('WTS', 'WeeklyStatus'), ('DTS', 'DailyStatus')], default='DTS', max_length=255),
        ),
    ]
