# Generated by Django 2.0.4 on 2018-05-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0005_scrumyuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumyuser',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
