# Generated by Django 2.0.4 on 2018-05-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0006_scrumyuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumyuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
