# Generated by Django 2.0.4 on 2018-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0007_auto_20180514_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumyuser',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
