# Generated by Django 2.0.4 on 2018-05-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0008_auto_20180515_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumyuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
