# Generated by Django 2.0.4 on 2018-06-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0009_scrumyuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumyuser',
            name='is_active',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
