# Generated by Django 2.0.4 on 2018-06-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0010_scrumyuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='bamidelescrumy.GoalStatus'),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumyuser', to='bamidelescrumy.ScrumyUser'),
        ),
    ]
