# Generated by Django 2.0.4 on 2018-06-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0011_auto_20180604_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumyuser',
            name='is_staff',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
