# Generated by Django 2.0.4 on 2018-06-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0012_scrumyuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalstatus',
            options={'verbose_name_plural': 'Goal Status'},
        ),
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={'verbose_name_plural': 'Scrumy Goals'},
        ),
        migrations.AlterModelOptions(
            name='scrumyuser',
            options={'verbose_name_plural': 'Scrumy User'},
        ),
    ]
