# Generated by Django 2.0.4 on 2018-06-04 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0013_auto_20180604_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bamidelescrumy.ScrumyUser'),
        ),
    ]
