# Generated by Django 2.0.4 on 2018-06-04 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0014_auto_20180604_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumygoals', to='bamidelescrumy.GoalStatus'),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumygoals', to='bamidelescrumy.ScrumyUser'),
        ),
    ]
