# Generated by Django 2.0.4 on 2018-06-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0015_auto_20180604_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumygoal', to='bamidelescrumy.GoalStatus'),
        ),
    ]
