# Generated by Django 2.0 on 2018-06-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0016_auto_20180605_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumyuser',
            name='is_admin',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
