# Generated by Django 2.0 on 2018-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0017_scrumyuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumyuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='scrumyuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='scrumyuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='scrumyuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scrumyuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrumyuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
