# Generated by Django 2.0 on 2018-06-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamidelescrumy', '0018_auto_20180619_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='status',
            new_name='status_id',
        ),
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='user',
            new_name='user_id',
        ),
    ]
